#!/usr/bin/env bash
set -euo pipefail

# === Root Check ===
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (sudo)" >&2
  exit 1
fi

# === Configuration ===
esp_path="/boot/EFI/refind"
icon_path="EFI/refind/themes/rEFInd-glassy/icons/os_linux.png"
conf_file="$esp_path/refind.conf"

# === Get UUID of the ESP device ===
boot_volume_uuid=$(findmnt -n -o SOURCE /boot | xargs blkid -s UUID -o value)
if [[ -z "$boot_volume_uuid" ]]; then
  echo "ERROR: Could not detect UUID for /boot mount." >&2
  exit 1
fi

# === Collect loader generations from files ===
gens_sorted=($(ls -1 /boot/loader/entries/nixos-generation-*.conf 2>/dev/null |
  sed -n 's/.*nixos-generation-\([0-9]*\)\.conf/\1/p' | sort -nr))

if [[ ${#gens_sorted[@]} -eq 0 ]]; then
  echo "ERROR: No valid loader entries found."
  exit 1
fi

current_gen="${gens_sorted[0]}"
fallback_gen="${gens_sorted[1]:-}"

# === Begin writing refind.conf ===
echo "# Auto-generated by generate-refind-config.sh" > "$conf_file"
cat >> "$conf_file" <<EOF
timeout 10
enable_touch
scanfor manual
default_selection "NixOS"
resolution 1280 720
include themes/rEFInd-glassy/theme.conf
EOF

# === Emit one full boot entry ===
emit_menuentry() {
  local label="$1"
  local entry_file="/boot/loader/entries/nixos-generation-${2}.conf"

  # Parse kernel, initrd, and options
  local kernel=$(grep -E '^linux ' "$entry_file" | awk '{print $2}' | xargs basename)
  local initrd=$(grep -E '^initrd ' "$entry_file" | awk '{print $2}' | xargs basename)
  local options=$(grep -E '^options ' "$entry_file" | cut -d' ' -f2-)

  echo >> "$conf_file"
  echo "menuentry \"$label\" {" >> "$conf_file"
  echo "    ostype Linux" >> "$conf_file"
  echo "    icon $icon_path" >> "$conf_file"
  echo "    volume $boot_volume_uuid" >> "$conf_file"
  echo "    loader /EFI/nixos/$kernel" >> "$conf_file"
  echo "    initrd /EFI/nixos/$initrd" >> "$conf_file"
  echo "    options \"$options\"" >> "$conf_file"
  echo "}" >> "$conf_file"
}

# === Emit current generation ===
emit_menuentry "NixOS" "$current_gen"

# === Emit fallback entry (only if available and different) ===
if [[ -n "$fallback_gen" && "$fallback_gen" != "$current_gen" ]]; then
  fallback_entry="/boot/loader/entries/nixos-generation-${fallback_gen}.conf"
  fallback_kernel=$(grep -E '^linux ' "$fallback_entry" | awk '{print $2}' | xargs basename)
  fallback_initrd=$(grep -E '^initrd ' "$fallback_entry" | awk '{print $2}' | xargs basename)
  fallback_options=$(grep -E '^options ' "$fallback_entry" | cut -d' ' -f2-)

  echo >> "$conf_file"
  echo "menuentry \"NixOS (Fallback)\" {" >> "$conf_file"
  echo "    ostype Linux" >> "$conf_file"
  echo "    icon $icon_path" >> "$conf_file"
  echo "    volume $boot_volume_uuid" >> "$conf_file"
  echo "    loader /EFI/nixos/$fallback_kernel" >> "$conf_file"
  echo "    initrd /EFI/nixos/$fallback_initrd" >> "$conf_file"
  echo "    options \"$fallback_options\"" >> "$conf_file"

  for gen in "${gens_sorted[@]}"; do
    # Only emit submenu entries for gens other than fallback and current
    if [[ "$gen" != "$current_gen" && "$gen" != "$fallback_gen" ]]; then
      submenu_file="/boot/loader/entries/nixos-generation-${gen}.conf"
      sub_kernel=$(grep -E '^linux ' "$submenu_file" | awk '{print $2}' | xargs basename)
      sub_initrd=$(grep -E '^initrd ' "$submenu_file" | awk '{print $2}' | xargs basename)
      sub_options=$(grep -E '^options ' "$submenu_file" | cut -d' ' -f2-)

      echo "    submenuentry \"NixOS ($gen)\" {" >> "$conf_file"
      echo "        loader /EFI/nixos/$sub_kernel" >> "$conf_file"
      echo "        initrd /EFI/nixos/$sub_initrd" >> "$conf_file"
      echo "        options \"$sub_options\"" >> "$conf_file"
      echo "    }" >> "$conf_file"
    fi
  done

    echo "}" >> "$conf_file"
fi

# === Windows entry ===
echo >> "$conf_file"
echo "menuentry \"Windows\" {" >> "$conf_file"
echo "    ostype Windows" >> "$conf_file"
echo "    EFI/refind/themes/rEFInd-glassy/icons/os_windows.png" >> "$conf_file"
echo "    volume 35bae7b0-32bc-4972-a5b1-d338bd9ddde1" >> "$conf_file"
echo "    loader /EFI/Microsoft/Boot/bootmgfw.efi" >> "$conf_file"
echo "}" >> "$conf_file"

echo "rEFInd config written to $conf_file"
